name: Check publish

# env:
#   IMAGE: alpine

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    paths-ignore:
      - '**/*.md'

jobs:
  setimage:
    runs-on: ubuntu-latest
    outputs:
      image: ${{ steps.set_image.outputs.IMAGE }}
    steps:
    - id: set_image
      run: echo "IMAGE=paritytech/ci-unified:bullseye-1.73.0" >> $GITHUB_OUTPUT


  check-publish:

    runs-on: ubuntu-latest
    container:
      image: alpine
      # image: ${{ needs.setimage.outputs.image }}
    steps:
      - name: ls before checkout
        run: |
          echo ${{ env.IMAGE }}

      - name: Print versions
        run: |
          rustc --version
          cargo --version
          uname -a


      # - name: install parity-publish
      #   run: cargo install parity-publish --profile dev

    #   - name: parity-publish check
    #     run: parity-publish check --allow-unpublished