name: Check publish

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
  check-publish:
    runs-on: ubuntu-latest
    container:
      image: paritytech/ci-unified:bullseye-1.70.0-2023-05-23-v20230706
    steps:
      - uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4.1.0

    #   - name: Rust Cache
    #     uses: Swatinem/rust-cache@v2.7.0

      - name: Install cargo-dylint
        uses: baptiste0928/cargo-install@21a18ba3bf4a184d1804e8b759930d3471b1c941 # v2.2.0
        with:
          crate: parity-publish
          args: --profile dev

    #   - name: install parity-publish
    #     run: cargo install parity-publish --profile dev

    #   - name: parity-publish check
    #     run: parity-publish check --allow-unpublished