name: Test environments

on:
  workflow_dispatch:

jobs:
  test-env:
    runs-on: ubuntu-latest
    environment: test
    steps:

      - name: Run tests
        run: |
          echo "Hello world!"
          echo "Access env SECRET BASH WAY: $ENV_SECRET1 or GHA WAY ${{ secrets.ENV_SECRET1 }}"
          echo "Access env variable BASH WAY: $ENV_VARIABLE or GHA WAY ${{ vars.ENV_VARIABLE }}"

  test-env2:
      runs-on: ubuntu-latest
      environment: test2
      steps:

        - name: Run tests
          run: |
            echo "Hello world!"
            echo "Access env SECRET BASH WAY: $ENV_SECRET1 or GHA WAY ${{ secrets.ENV_SECRET1 }}"
            echo "Access env variable BASH WAY: $ENV_VARIABLE or GHA WAY ${{ vars.ENV_VARIABLE }}"
