name: Test environments

on:
  workflow_dispatch:

jobs:
  test-env:
    runs-on: ubuntu-latest
    environment: test
    steps:

      - name: Run tests
        run: |
          echo "Hello world!"
          echo "Access env SECRET: $ENV_SECRET1"
          echo "Access env variable: $ENV_VARIABLE"

  test-env2:
      runs-on: ubuntu-latest
      environment: test2
      steps:

        - name: Run tests
          run: |
            echo "Hello world!"
            echo "Access env SECRET: $ENV_SECRET1"
            echo "Access env variable: $ENV_VARIABLE"
